inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/data_schema.rb
    - db/schema.rb
    - frontend/node_modules/**/*
    - node_modules/**/*
    - spec/dummy/node_modules/**/*
  NewCops: enable
  TargetRubyVersion: 3.2

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Lint/MixedCaseRange:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/NonAtomicFileOperation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/InclusiveLanguage:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

# .find_each is not the same as .each
Rails/FindEach:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInLet:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/Output:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/ArrayCoercion:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Will report offences for many places that are much more readable without using a guard clause
Style/GuardClause:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true

Style/WordArray:
  Enabled: false
